apiVersion: goharbor.io/v1alpha2
kind: Harbor
metadata:
  name: sample
spec:
  trivy:
    skipUpdate: false
    storage:
      reportsPersistentVolume:
        claimName: sample-harbor-trivy-reports
      cachePersistentVolume:
        claimName: sample-harbor-trivy-cache
