apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: controller
  newName: goharbor/harbor-operator
  newTag: dev

configMapGenerator:
- literals:
  - HARBOR_CONTROLLER_MAX_RECONCILE=1
  - HARBOR_CONTROLLER_WATCH_CHILDREN=true
  name: operator-config
- files:
  - assets/registry-config.yaml.tmpl
  name: registry-template

patchesStrategicMerge:
- patches-configuration.yaml

resources:
- manager.yaml
