apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sample: "true"

secretGenerator:
- name: notary-signer-aliases
  literals:
  - default=the-default-password
  - oldalias1=anOldPassword
  type: "goharbor.io/notary-signer-aliases"

resources:
- notarysigner-certificate.yaml
- notarysigner-certificate-issuer.yaml
- goharbor_v1alpha3_notarysigner.yaml

bases:
- ../../kustomizeconfig
