apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.serviceAccountName" . | quote }}'
  namespace: '{{ .Release.Namespace | quote }}'
