apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: POSTGRES_SECRETS_TEMPLATE
          value: '{username}.{cluster}.credentials.{tprkind}.{tprgroup}'
        - name: CONFIGURATION_FROM
          value: 'env,file:/etc/harbor-operator/config.yaml'
        - name: CLASSNAME
          value: '{{ .Values.harborClass | quote }}'
        - name: LOG_LEVEL
          value: '{{ .Values.logLevel | quote }}'
        volumeMounts:
        - mountPath: /etc/harbor-operator
          name: configuration
          readOnly: true
      volumes:
      - name: configuration
        configMap:
          name: '{{ include "chart.fullname" . }}-config'
