# This file is for teaching kustomize how to substitute name in ChartMuseum
nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/auth/basicAuthRef
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/auth/bearer/certificateRef
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/cache/redis/passwordRef
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/chart/storage/amazon/accessSecretRef
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/chart/storage/openstack/passwordRef
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/server/tls/certificateRef
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/imagePullSecrets/items/name

- kind: PersistentVolumeClaim
  version: v1
  fieldSpecs:
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/chart/storage/filesystem/volumeSource/persistentVolumeClaim/claimName

- kind: ServiceAccount
  version: v1
  fieldSpecs:
  - kind: ChartMuseum
    group: goharbor.io
    path: spec/serviceAccountName
