apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sample: "true"

resources:
- https.yaml
- internal_tls.yaml
- service_token_issuer.yaml
- storage.yaml
- goharbor_v1alpha3_harbor.yaml

secretGenerator:
- name: core-secret
  literals:
  - secret=unsecure-core-secret
  type: "goharbor.io/single-secret"
- name: csrf-key
  literals:
  - key=12345678901234567890123456789012
  type: "goharbor.io/csrf"
- name: admin-core-secret
  literals:
  - secret=Harbor12345
  type: "goharbor.io/single-secret"
- name: core-database-encryption
  literals:
    - secret=1234567890123456
  type: "goharbor.io/single-secret"
- name: jobservice-secret
  literals:
  - secret=unsecure-jobservice-secret
  type: "goharbor.io/single-secret"

bases:
- ../../kustomizeconfig
