apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: sample-server
spec:
  secretName: sample-server
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - goharbor
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - client auth
  dnsNames:
  - sample-notaryserver
  issuerRef:
    name: sample-signer
