apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override namespace
namespace: harbor-operator-ns

# Common annotations
commonAnnotations:
  goharbor.io/operator-version: "v1.3.0"
  goharbor.io/deploy-mode: "harbor"
  goharbor.io/deploy-engine: "Kustomization"

# All the referred deployment manifests
resources:
  - namespace.yaml
  - ../../config/default # harbor operator

# If you have to override the image path, uncomment this patch and also change the image paths in the patch/image-source.yaml file.
# Then rebuild.
# patchesStrategicMerge:
#  - patch/image-source.yaml

images:
  - name: goharbor/harbor-operator
    newName: ghcr.io/goharbor/harbor-operator
    newTag: dev_master