apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sample-public-certificate
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-public-certificate
spec:
  isCA: true
  issuerRef:
    name: sample-public-certificate
  secretName: sample-public-certificate
  dnsNames:
  - core.harbor.domain
  - notary.harbor.domain
