apiVersion: goharbor.io/v1alpha3
kind: NotaryServer
metadata:
  name: sample
spec:
  migration:
    github:
      credentialsRef: github-credentials
      owner: theupdateframework
      repositoryName: notary
      path: /migrations/server/postgresql
      reference: v0.6.1
  storage:
    postgres:
      hosts:
      - host: harbor-database-postgresql
        port: 5432
      username: postgres
      passwordRef: harbor-database-password
      database: notarysigner
      parameters:
        sslmode: disable
  trustService: {}
