apiVersion: goharbor.io/v1beta1
kind: JobService
metadata:
  annotations:
    goharbor.io/network-policies: "false"
    harbor.goharbor.io/version: 2.4.0
  creationTimestamp: null
  name: example-harbor
  namespace: default
spec:
  core:
    secretRef: example-harbor-core-secret
    url: http://example-harbor-core:80
  image: goharbor/harbor-jobservice:v2.4.0-patch1
  jobLoggers:
    files:
    - level: INFO
      sweeper: 14h0m0s
  loggers:
    stdout:
      level: INFO
  registry:
    controllerURL: http://example-harbor-registryctl:80
    credentials:
      passwordRef: example-harbor-registry-basicauth
      username: harbor_registry_user
    url: http://example-harbor-registry
  resources: {}
  secretRef: example-harbor-jobservice-secret
  storage:
    scanDataExports:
      volumeSource:
        emptyDir: {}
  tokenService:
    url: http://example-harbor-core/service/token
  workerPool:
    redisPool:
      database: 2
      host: 127.0.0.1
      port: 3306
status:
  conditions: []
  operator: {}
