# https://github.com/coreos/clair/blob/master/config.yaml.sample
# https://github.com/goharbor/harbor/blob/master/make/photon/prepare/templates/clair/config.yaml.jinja
clair:
  database:
    type: pgsql
    options:
      source: postgresql://{{ env.Getenv "username" }}:{{ env.Getenv "password" }}@{{ env.Getenv "host" }}:{{ env.Getenv "port" "5432" }}/{{ env.Getenv "database" }}
        {{- if gt ( len ( env.Getenv "ssl" ) ) 0 -}}?sslmode={{ env.Getenv "ssl" }}{{- end }}
  updater:
    interval: 0s
    enabledupdaters:
{{ env.Getenv "vulnsrc" | data.JSONArray | data.ToYAML | strings.Indent 3 "  " -}}
  api:
    port: 6060
    healthport: 6061
    timeout: 5m0s
